"""alter drs table yeild_amount to crop_yield

Revision ID: 8f0ee7dad192
Revises: 11252b877df4
Create Date: 2024-06-06 18:58:20.587152+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f0ee7dad192"
down_revision = "11252b877df4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drought_resistant_seed_yield",
        sa.Column("crop_yield", sa.Float(), nullable=True),
    )
    op.drop_column("drought_resistant_seed_yield", "yield_amount")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drought_resistant_seed_yield",
        sa.Column(
            "yield_amount",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("drought_resistant_seed_yield", "crop_yield")
    # ### end Alembic commands ###
