"""add crop rotation table

Revision ID: 100839656a13
Revises: 96392fc1bec7
Create Date: 2024-07-22 17:16:00.606574+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "100839656a13"
down_revision = "96392fc1bec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_rotation",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("planting_date", sa.Date(), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column("crop_yield", sa.Float(), nullable=True),
        sa.Column("yield_unit", sa.String(length=50), nullable=True),
        sa.Column("seeding_rate", sa.Float(), nullable=True),
        sa.Column("seeding_rate_unit", sa.String(length=50), nullable=True),
        sa.Column("fertilizer_application", sa.Text(), nullable=True),
        sa.Column("research_ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_ref_id"],
            ["research.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crop_rotation")
    # ### end Alembic commands ###
