"""add_field_coordinate

Revision ID: efc2982512ec
Revises: de7b885ec7b4
Create Date: 2024-02-09 15:12:56.494769+00:00

"""

from alembic import op
import sqlalchemy as sa
from app.utils.db import Geometry

# revision identifiers, used by Alembic.
revision = "efc2982512ec"
down_revision = "de7b885ec7b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields",
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
    )
    op.drop_index("ix_fields_field_shape", table_name="fields")
    op.create_index(
        "ix_fields_coordinates",
        "fields",
        ["coordinates"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fields_coordinates", table_name="fields", postgresql_using="gist")
    op.create_index("ix_fields_field_shape", "fields", ["field_shape"], unique=False)
    op.drop_column("fields", "coordinates")
    # ### end Alembic commands ###
