"""add geostream sensors

Revision ID: d1d18f24e794
Revises: efc2982512ec
Create Date: 2024-03-28 17:36:50.181397+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d1d18f24e794"
down_revision = "efc2982512ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("depth", sa.String(length=200), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("field_ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_ref_id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_geospatial_index(
        "ix_fields_coordinates", table_name="fields", column_name="coordinates"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_index(
        "ix_fields_coordinates",
        "fields",
        ["coordinates"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_table("sensors")
    # ### end Alembic commands ###
