"""alter_name_field

Revision ID: de7b885ec7b4
Revises: af0d80534e45
Create Date: 2024-01-23 19:38:13.608262+00:00

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from app.utils.db import Geometry


# revision identifiers, used by Alembic.
revision = "de7b885ec7b4"
down_revision = "af0d80534e45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields",
        sa.Column(
            "field_shape",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
    )
    op.drop_index("idx_fields_location", table_name="fields")
    op.create_index(
        "ix_fields_field_shape",
        "fields",
        ["field_shape"],
        unique=False,
        postgresql_using="gist",
    )
    op.drop_column("fields", "location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_fields_field_shape", table_name="fields", postgresql_using="gist")
    op.create_index("idx_fields_location", "fields", ["location"], unique=False)
    op.drop_column("fields", "field_shape")
    # ### end Alembic commands ###
