"""add crop field to crop rotation table

Revision ID: 8ebfae34199a
Revises: 0330e4697600
Create Date: 2024-09-24 13:55:59.535680+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ebfae34199a"
down_revision = "0330e4697600"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crop_rotation", sa.Column("crop", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crop_rotation", "crop")
    # ### end Alembic commands ###
