"""alter sensor table to add type


Revision ID: 96392fc1bec7
Revises: 8f0ee7dad192
Create Date: 2024-06-07 19:29:22.735758+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "96392fc1bec7"
down_revision = "8f0ee7dad192"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensors", sa.Column("sensor_type", sa.String(length=200), nullable=True)
    )
    op.alter_column(
        "sensors", "depth", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sensors", "depth", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("sensors", "sensor_type")
    # ### end Alembic commands ###
