"""alter_name

Revision ID: af0d80534e45
Revises: 0906792b574b
Create Date: 2024-01-23 17:49:01.859589+00:00

"""

import geoalchemy2

from alembic import op

# revision identifiers, used by Alembic.
revision = "af0d80534e45"
down_revision = "0906792b574b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fields",
        "location",
        existing_type=geoalchemy2.types.Geography(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
        ),
        type_=geoalchemy2.types.Geography(
            geometry_type="POLYGON", from_text="ST_GeogFromText", name="geography"
        ),
        existing_nullable=False,
    )
    op.drop_index("ix_fields_location", table_name="fields")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_fields_location", "fields", ["location"], unique=False)
    op.alter_column(
        "fields",
        "location",
        existing_type=geoalchemy2.types.Geography(
            geometry_type="POLYGON", from_text="ST_GeogFromText", name="geography"
        ),
        type_=geoalchemy2.types.Geography(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
