name: Run unit test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, edited ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    # Run the job in this container
    container: python:3.8-bullseye

    env:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_TEST_DB: test_direct4ag

    # Service containers to run with `pytest` job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:13-master
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install -y postgresql-client

      - name: Install python requirements
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run Unit Testing
        run: pytest app/tests
        env:
          PGHOST: ${{ env.POSTGRES_SERVER }}
          PGPORT: ${{ env.POSTGRES_PORT }}
          PGUSER: ${{ env.POSTGRES_USER }}
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
          # Environment variables required by FastAPI
          SERVER_HOST: http://localhost
          ROUTER_PREFIX: /direct4ag
          POSTGRES_DB: test_direct4ag
          FIRST_SUPERUSER: admin@example.com
          FIRST_SUPERUSER_PASSWORD: secret_password
